events { worker_connections 1024; }

stream {
    upstream kasir_tcp {
        server app1:3000;
        server app2:3000;
        server app3:3000;
    }

    server {
        listen 8080;
        proxy_pass kasir_tcp;
    }
}
